package com.calcge.constant;

public enum BuffType {
	ATK,
	ATK_PERCENTAGE,
	DEF,
	DEF_PERCENTAGE,
	HP,
	HP_PERCENTAGE,
	ELEMENTAL_MASTERY,
	ENERGY_RECHARGE,
	CRIT_RATE,
	CRIT_DAMAGE,
	PYRO_BONUS_DAMAGE,
	HYDRO_BONUS_DAMAGE,
	CRYO_BONUS_DAMAGE,
	ELECTRO_BONUS_DAMAGE,
	ANEMO_BONUS_DAMAGE,
	DENDRO_BONUS_DAMAGE,
	GEO_BONUS_DAMAGE
}
